dist: xenial
sudo: required

language: python
python:
  - "3.7"

install:
  - sudo apt-get install --no-install-recommends build-essential
  - pip install git+https://github.com/JoshKarpel/simulacra.git
  - pip install --upgrade -r requirements-dev.txt
  - pip install -e .
  - python -c "import modulation"
  - pip install codecov

script:
  - pytest --cov -n 2 -- tests/

after_success:
  - codecov
